## CreateYourOwnMenus configuration file
##
## whitelist-commands - If you specify a list of whitelisted commands, then only 
## these commands can be used in menu scripts. All others will fail.
##
## blacklist-commands - If you specify a list of blacklisted commands, then none
## of these commands can be used in menu scripts.
---
blacklist-commands:
  - op

## servercommands can be seperately enabled with, hidden playercommands also won't work with this fix
## for possible hacking :P, uncomment next line
# only-playercommands: false